//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeLife.Aplicacion.Idiomas.Localizacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeLife.Aplicacion.Idiomas.Localizacion.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicación: BeLife..
        /// </summary>
        public static string AcercaDeForm_Aplicacion {
            get {
                return ResourceManager.GetString("AcercaDeForm_Aplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrantes del grupo:.
        /// </summary>
        public static string AcercaDeForm_Equipo {
            get {
                return ResourceManager.GetString("AcercaDeForm_Equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profesor: {0}.
        /// </summary>
        public static string AcercaDeForm_Profesor {
            get {
                return ResourceManager.GetString("AcercaDeForm_Profesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programado para:.
        /// </summary>
        public static string AcercaDeForm_ProgramadoPara {
            get {
                return ResourceManager.GetString("AcercaDeForm_ProgramadoPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ramo: Desarrollo de software de escritorio y gestión..
        /// </summary>
        public static string AcercaDeForm_Ramo {
            get {
                return ResourceManager.GetString("AcercaDeForm_Ramo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version: v0.0.2.
        /// </summary>
        public static string AcercaDeForm_Version {
            get {
                return ResourceManager.GetString("AcercaDeForm_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite al usuario cambiar el estilo de la aplicación, los estilos disponibles pueden variar entre colores claros y color de alto contraste..
        /// </summary>
        public static string Ayuda_CambiarColor {
            get {
                return ResourceManager.GetString("Ayuda_CambiarColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite cambiar el idioma de la aplicación de español a ingles o viceversa..
        /// </summary>
        public static string Ayuda_CambiarIdioma {
            get {
                return ResourceManager.GetString("Ayuda_CambiarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite buscar clientes por diferentes criterios, estos pueden ser buscar por rut, por estado civil, por sexo o simplemente listar los clientes disponibles..
        /// </summary>
        public static string Ayuda_ListadoClientes {
            get {
                return ResourceManager.GetString("Ayuda_ListadoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite realizar busquedas de contratos, estas pueden ser por número de contrato, por rut del cliente o por número de poliza..
        /// </summary>
        public static string Ayuda_ListadoContratos {
            get {
                return ResourceManager.GetString("Ayuda_ListadoContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta opción permite ingresar nuevos clientes, editar información de estos o eliminar la información de un cliente que no posee contratos..
        /// </summary>
        public static string Ayuda_MaestroDeClientes {
            get {
                return ResourceManager.GetString("Ayuda_MaestroDeClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite realizar acciones con los contratos, puede crear un nuevo contrato a un cliente, editar la información de un contrato existente o terminar la vigencia de un contrato activo..
        /// </summary>
        public static string Ayuda_MaestroDeContratos {
            get {
                return ResourceManager.GetString("Ayuda_MaestroDeContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Cliente {0} existe en la base de datos..
        /// </summary>
        public static string BuscarCliente_Existente {
            get {
                return ResourceManager.GetString("BuscarCliente_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Cliente que intenta buscar no esta registrado en la base de datos..
        /// </summary>
        public static string BuscarCliente_NoExiste {
            get {
                return ResourceManager.GetString("BuscarCliente_NoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato número {0} ya se encuentra registrado en la base de datos..
        /// </summary>
        public static string BuscarContrato_Existente {
            get {
                return ResourceManager.GetString("BuscarContrato_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contrato que intenta buscar no existe en la base de datos.
        /// </summary>
        public static string BuscarContrato_NoExiste {
            get {
                return ResourceManager.GetString("BuscarContrato_NoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente {0} ya posee un contrato con el plan {1}, este se encuentra vigente hasta el {2}..
        /// </summary>
        public static string BuscarContratoVigente_Existente {
            get {
                return ResourceManager.GetString("BuscarContratoVigente_Existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente no posee un contrato asociado vigente con el plan seleccionado..
        /// </summary>
        public static string BuscarContratoVigente_NoExiste {
            get {
                return ResourceManager.GetString("BuscarContratoVigente_NoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por estado civil..
        /// </summary>
        public static string FiltrosClientes_PorEstadoCivil {
            get {
                return ResourceManager.GetString("FiltrosClientes_PorEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por rut de cliente..
        /// </summary>
        public static string FiltrosClientes_PorRut {
            get {
                return ResourceManager.GetString("FiltrosClientes_PorRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por sexo..
        /// </summary>
        public static string FiltrosClientes_PorSexo {
            get {
                return ResourceManager.GetString("FiltrosClientes_PorSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin filtro..
        /// </summary>
        public static string FiltrosClientes_SinFiltro {
            get {
                return ResourceManager.GetString("FiltrosClientes_SinFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por número de contrato..
        /// </summary>
        public static string FiltrosContratos_PorNumeroContrato {
            get {
                return ResourceManager.GetString("FiltrosContratos_PorNumeroContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por número de poliza..
        /// </summary>
        public static string FiltrosContratos_PorNumeroDePoliza {
            get {
                return ResourceManager.GetString("FiltrosContratos_PorNumeroDePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por rut cliente..
        /// </summary>
        public static string FiltrosContratos_PorRutCliente {
            get {
                return ResourceManager.GetString("FiltrosContratos_PorRutCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin filtro..
        /// </summary>
        public static string FiltrosContratos_SinFiltro {
            get {
                return ResourceManager.GetString("FiltrosContratos_SinFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actualizado.
        /// </summary>
        public static string Grabar_AccionActualizado {
            get {
                return ResourceManager.GetString("Grabar_AccionActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actualizar.
        /// </summary>
        public static string Grabar_AccionActualizar {
            get {
                return ResourceManager.GetString("Grabar_AccionActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a creado.
        /// </summary>
        public static string Grabar_AccionCreado {
            get {
                return ResourceManager.GetString("Grabar_AccionCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a crear.
        /// </summary>
        public static string Grabar_AccionCrear {
            get {
                return ResourceManager.GetString("Grabar_AccionCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eliminado.
        /// </summary>
        public static string Grabar_AccionEliminado {
            get {
                return ResourceManager.GetString("Grabar_AccionEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eliminar.
        /// </summary>
        public static string Grabar_AccionEliminar {
            get {
                return ResourceManager.GetString("Grabar_AccionEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente {0} ha sido {1}..
        /// </summary>
        public static string GrabarCliente_Correctamente {
            get {
                return ResourceManager.GetString("GrabarCliente_Correctamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido posible {0} el cliente {1}, intente nuevamente..
        /// </summary>
        public static string GrabarCliente_Error {
            get {
                return ResourceManager.GetString("GrabarCliente_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El contrato número {0} fue {1} correctamente..
        /// </summary>
        public static string GrabarContrato_Correctamente {
            get {
                return ResourceManager.GetString("GrabarContrato_Correctamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido posible {0} el contrato número {1}, intente nuevamente..
        /// </summary>
        public static string GrabarContrato_Error {
            get {
                return ResourceManager.GetString("GrabarContrato_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español (España).
        /// </summary>
        public static string Idioma_Español {
            get {
                return ResourceManager.GetString("Idioma_Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés (Estados Unidos).
        /// </summary>
        public static string Idioma_Ingles {
            get {
                return ResourceManager.GetString("Idioma_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string Idioma_Predeterminado {
            get {
                return ResourceManager.GetString("Idioma_Predeterminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una comuna..
        /// </summary>
        public static string ItemInicial_ComunaCorrecta {
            get {
                return ResourceManager.GetString("ItemInicial_ComunaCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga comuna..
        /// </summary>
        public static string ItemInicial_ComunaError {
            get {
                return ResourceManager.GetString("ItemInicial_ComunaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un estado civil..
        /// </summary>
        public static string ItemInicial_EstadoCivil_Correcto {
            get {
                return ResourceManager.GetString("ItemInicial_EstadoCivil_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga estado civil..
        /// </summary>
        public static string ItemInicial_EstadoCivil_Error {
            get {
                return ResourceManager.GetString("ItemInicial_EstadoCivil_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un plan..
        /// </summary>
        public static string ItemInicial_Plan_Correcto {
            get {
                return ResourceManager.GetString("ItemInicial_Plan_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga plan..
        /// </summary>
        public static string ItemInicial_Plan_Error {
            get {
                return ResourceManager.GetString("ItemInicial_Plan_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una región..
        /// </summary>
        public static string ItemInicial_RegionCorrecta {
            get {
                return ResourceManager.GetString("ItemInicial_RegionCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga región..
        /// </summary>
        public static string ItemInicial_RegionError {
            get {
                return ResourceManager.GetString("ItemInicial_RegionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un sexo..
        /// </summary>
        public static string ItemInicial_Sexo_Correcto {
            get {
                return ResourceManager.GetString("ItemInicial_Sexo_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga sexo..
        /// </summary>
        public static string ItemInicial_Sexo_Error {
            get {
                return ResourceManager.GetString("ItemInicial_Sexo_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un tipo de plan..
        /// </summary>
        public static string ItemInicial_TipoPlan_Correcto {
            get {
                return ResourceManager.GetString("ItemInicial_TipoPlan_Correcto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga tipo plan..
        /// </summary>
        public static string ItemInicial_TipoPlan_Error {
            get {
                return ResourceManager.GetString("ItemInicial_TipoPlan_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una marca..
        /// </summary>
        public static string ItemInicial_Vehiculo_MarcaCorrecto {
            get {
                return ResourceManager.GetString("ItemInicial_Vehiculo_MarcaCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga marca..
        /// </summary>
        public static string ItemInicial_Vehiculo_MarcaError {
            get {
                return ResourceManager.GetString("ItemInicial_Vehiculo_MarcaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un modelo..
        /// </summary>
        public static string ItemInicial_Vehiculo_ModeloCorrecto {
            get {
                return ResourceManager.GetString("ItemInicial_Vehiculo_ModeloCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error carga modelo..
        /// </summary>
        public static string ItemInicial_Vehiculo_ModeloError {
            get {
                return ResourceManager.GetString("ItemInicial_Vehiculo_ModeloError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EstadoCivil:.
        /// </summary>
        public static string ListadoClientes_CampoEstadoCivil {
            get {
                return ResourceManager.GetString("ListadoClientes_CampoEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rut:.
        /// </summary>
        public static string ListadoClientes_CampoRut {
            get {
                return ResourceManager.GetString("ListadoClientes_CampoRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo:.
        /// </summary>
        public static string ListadoClientes_CampoSexo {
            get {
                return ResourceManager.GetString("ListadoClientes_CampoSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de contrato:.
        /// </summary>
        public static string ListadoContratos_EtiquetaValorFiltro_PorNumeroDeContrato {
            get {
                return ResourceManager.GetString("ListadoContratos_EtiquetaValorFiltro_PorNumeroDeContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de poliza:.
        /// </summary>
        public static string ListadoContratos_EtiquetaValorFiltro_PorNumeroDePoliza {
            get {
                return ResourceManager.GetString("ListadoContratos_EtiquetaValorFiltro_PorNumeroDePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rut:.
        /// </summary>
        public static string ListadoContratos_EtiquetaValorFiltro_PorRut {
            get {
                return ResourceManager.GetString("ListadoContratos_EtiquetaValorFiltro_PorRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar el cliente {0}, debido a que el cliente posee {1} contratos registrados..
        /// </summary>
        public static string MaestroClientes_Eliminar_NoPuedeEliminarCliente {
            get {
                return ResourceManager.GetString("MaestroClientes_Eliminar_NoPuedeEliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de eliminar el cliente {0}?.
        /// </summary>
        public static string MaestroClientes_Eliminar_PreguntaSiQuiereEliminar {
            get {
                return ResourceManager.GetString("MaestroClientes_Eliminar_PreguntaSiQuiereEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando cliente..
        /// </summary>
        public static string MaestroClientes_MensajeModoBusqueda {
            get {
                return ResourceManager.GetString("MaestroClientes_MensajeModoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando información de cliente {0}..
        /// </summary>
        public static string MaestroClientes_MensajeModoEdicion {
            get {
                return ResourceManager.GetString("MaestroClientes_MensajeModoEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creando nuevo cliente..
        /// </summary>
        public static string MaestroClientes_MensajeModoNuevoCliente {
            get {
                return ResourceManager.GetString("MaestroClientes_MensajeModoNuevoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rut ingresado ya existe en la base de datos..
        /// </summary>
        public static string MaestroClientes_MensajeRutExistente {
            get {
                return ResourceManager.GetString("MaestroClientes_MensajeRutExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rut ingresado no existe..
        /// </summary>
        public static string MaestroClientes_MensajeRutNoExiste {
            get {
                return ResourceManager.GetString("MaestroClientes_MensajeRutNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de termino de contrato ha sido fijada como {0}, proceda a grabar la información del contrato presionando el botón [Grabar], si cancela la acción con el botón [Cancelar], el termino de contrato no tendra efecto alguno y este seguirá vigente..
        /// </summary>
        public static string MaestroContratos_MensajeCambioFechaDETerminoDeContrato {
            get {
                return ResourceManager.GetString("MaestroContratos_MensajeCambioFechaDETerminoDeContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha confirmado la busqueda de la información del cliente, favor presione el botón buscar rut para cargar la información..
        /// </summary>
        public static string MaestroContratos_MensajeDatosClienteSinConfirmar {
            get {
                return ResourceManager.GetString("MaestroContratos_MensajeDatosClienteSinConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscando contrato..
        /// </summary>
        public static string MaestroContratos_MensajeModoBusqueda {
            get {
                return ResourceManager.GetString("MaestroContratos_MensajeModoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando contrato del cliente {0}.
        /// </summary>
        public static string MaestroContratos_MensajeModoEdicion {
            get {
                return ResourceManager.GetString("MaestroContratos_MensajeModoEdicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creando nuevo contrato..
        /// </summary>
        public static string MaestroContratos_MensajeModoNuevoContrato {
            get {
                return ResourceManager.GetString("MaestroContratos_MensajeModoNuevoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de dar termino al contrato número {0} del cliente {1} que tiene asignado el plan {2}?.
        /// </summary>
        public static string MaestroContratos_MensajePreguntaDETerminoDeContrato {
            get {
                return ResourceManager.GetString("MaestroContratos_MensajePreguntaDETerminoDeContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La antiguedad no es correcta, debe comprender los valores entre {0} y {1}..
        /// </summary>
        public static string MensajeValidacion_AntiguedadInvalida {
            get {
                return ResourceManager.GetString("MensajeValidacion_AntiguedadInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} admite solo valores numéricos..
        /// </summary>
        public static string MensajeValidacion_CampoSoloNumeros {
            get {
                return ResourceManager.GetString("MensajeValidacion_CampoSoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} no puede quedar vacio..
        /// </summary>
        public static string MensajeValidacion_CampoVacio {
            get {
                return ResourceManager.GetString("MensajeValidacion_CampoVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código postal no es valido, debe ingresar un valor entre 1000000 y 9999999..
        /// </summary>
        public static string MensajeValidacion_CodigoPostalInvalido {
            get {
                return ResourceManager.GetString("MensajeValidacion_CodigoPostalInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de la patente no es válido.
        /// </summary>
        public static string MensajeValidacion_FormatoPatenteInvalida {
            get {
                return ResourceManager.GetString("MensajeValidacion_FormatoPatenteInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato del rut incorrecto, ejemplo 12345678-9..
        /// </summary>
        public static string MensajeValidacion_FormatoRutIncorrecto {
            get {
                return ResourceManager.GetString("MensajeValidacion_FormatoRutIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente debe tener al menos 18 años de edad..
        /// </summary>
        public static string MensajeValidacion_MenorDeEdad {
            get {
                return ResourceManager.GetString("MensajeValidacion_MenorDeEdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rut ingresado no es correcto..
        /// </summary>
        public static string MensajeValidacion_RutIncorrecto {
            get {
                return ResourceManager.GetString("MensajeValidacion_RutIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un {0}..
        /// </summary>
        public static string MensajeValidacion_SeleccionCombobox {
            get {
                return ResourceManager.GetString("MensajeValidacion_SeleccionCombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo valor base admite solo numeros..
        /// </summary>
        public static string MensajeValidacion_SoloNumeros {
            get {
                return ResourceManager.GetString("MensajeValidacion_SoloNumeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor base del plan   debe ser mayor a 0 UF..
        /// </summary>
        public static string MensajeValidacion_ValorBaseMenorQueCero {
            get {
                return ResourceManager.GetString("MensajeValidacion_ValorBaseMenorQueCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Abortar.
        /// </summary>
        public static string Msgbox_Abortar {
            get {
                return ResourceManager.GetString("Msgbox_Abortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Aceptar.
        /// </summary>
        public static string Msgbox_Aceptar {
            get {
                return ResourceManager.GetString("Msgbox_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Msgbox_Cancelar {
            get {
                return ResourceManager.GetString("Msgbox_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Ignorar.
        /// </summary>
        public static string Msgbox_Ignorar {
            get {
                return ResourceManager.GetString("Msgbox_Ignorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;No.
        /// </summary>
        public static string Msgbox_No {
            get {
                return ResourceManager.GetString("Msgbox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Reintentar.
        /// </summary>
        public static string Msgbox_Reintentar {
            get {
                return ResourceManager.GetString("Msgbox_Reintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Sí.
        /// </summary>
        public static string Msgbox_si {
            get {
                return ResourceManager.GetString("Msgbox_si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de salir?.
        /// </summary>
        public static string principalForm_MensajeSalida {
            get {
                return ResourceManager.GetString("principalForm_MensajeSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} {1} encontrados..
        /// </summary>
        public static string ResultadoDataGrid_ItemsEncontrados {
            get {
                return ResourceManager.GetString("ResultadoDataGrid_ItemsEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay {0} disponibles..
        /// </summary>
        public static string ResultadoDataGrid_SinRegistros {
            get {
                return ResourceManager.GetString("ResultadoDataGrid_SinRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clientes.
        /// </summary>
        public static string ResultadoDataGrid_TipoCliente {
            get {
                return ResourceManager.GetString("ResultadoDataGrid_TipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a contratos.
        /// </summary>
        public static string ResultadoDataGrid_TipoContrato {
            get {
                return ResourceManager.GetString("ResultadoDataGrid_TipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claro.
        /// </summary>
        public static string Tema_Claro {
            get {
                return ResourceManager.GetString("Tema_Claro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar a tema oscuro..
        /// </summary>
        public static string Tema_Mensaje_ClaroOscuro {
            get {
                return ResourceManager.GetString("Tema_Mensaje_ClaroOscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar a tema claro..
        /// </summary>
        public static string Tema_Mensaje_OscuroClaro {
            get {
                return ResourceManager.GetString("Tema_Mensaje_OscuroClaro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oscuro.
        /// </summary>
        public static string Tema_Oscuro {
            get {
                return ResourceManager.GetString("Tema_Oscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antiguedad.
        /// </summary>
        public static string TextoPrima_Antiguedad {
            get {
                return ResourceManager.GetString("TextoPrima_Antiguedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad : .
        /// </summary>
        public static string TextoPrima_Edad {
            get {
                return ResourceManager.GetString("TextoPrima_Edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado civil : .
        /// </summary>
        public static string TextoPrima_EstadoCivil {
            get {
                return ResourceManager.GetString("TextoPrima_EstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargos --&gt; .
        /// </summary>
        public static string TextoPrima_Recargo {
            get {
                return ResourceManager.GetString("TextoPrima_Recargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region.
        /// </summary>
        public static string TextoPrima_Region {
            get {
                return ResourceManager.GetString("TextoPrima_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo : .
        /// </summary>
        public static string TextoPrima_Sexo {
            get {
                return ResourceManager.GetString("TextoPrima_Sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor contenido.
        /// </summary>
        public static string TextoPrima_ValorContenido {
            get {
                return ResourceManager.GetString("TextoPrima_ValorContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor vivienda.
        /// </summary>
        public static string TextoPrima_ValorVivienda {
            get {
                return ResourceManager.GetString("TextoPrima_ValorVivienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Atención..
        /// </summary>
        public static string TituloMensajes_Atencion {
            get {
                return ResourceManager.GetString("TituloMensajes_Atencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error..
        /// </summary>
        public static string TituloMensajes_Error {
            get {
                return ResourceManager.GetString("TituloMensajes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra información sobre aplicativo BeLife..
        /// </summary>
        public static string ToolTip_AcercaDEForm {
            get {
                return ResourceManager.GetString("ToolTip_AcercaDEForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente de seguros enseñando planes existentes a sus clientes..
        /// </summary>
        public static string ToolTip_ListadoDeClientes {
            get {
                return ResourceManager.GetString("ToolTip_ListadoDeClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente de seguros mostrando contratos existentes a sus clientes..
        /// </summary>
        public static string ToolTip_ListadoDeContratos {
            get {
                return ResourceManager.GetString("ToolTip_ListadoDeContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compañía de seguros BeLife..
        /// </summary>
        public static string ToolTip_LogoBeLiffe {
            get {
                return ResourceManager.GetString("ToolTip_LogoBeLiffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen que representa un conjunto de asesores de seguros esperando para la atención de un cliente..
        /// </summary>
        public static string ToolTip_MaestroDeClientes {
            get {
                return ResourceManager.GetString("ToolTip_MaestroDeClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen que representa un contrato firmado entre un cliente y su asesor de seguros..
        /// </summary>
        public static string ToolTip_MaestroDeContratos {
            get {
                return ResourceManager.GetString("ToolTip_MaestroDeContratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permite cambiar los ajustes de la aplicación..
        /// </summary>
        public static string ToolTip_PreferenciasForm {
            get {
                return ResourceManager.GetString("ToolTip_PreferenciasForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asesor de seguros ofreciendo una poliza de seguros a matrimonio..
        /// </summary>
        public static string ToolTip_PrincipalForm {
            get {
                return ResourceManager.GetString("ToolTip_PrincipalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de la aplicación..
        /// </summary>
        public static string ToolTip_SalirButton {
            get {
                return ResourceManager.GetString("ToolTip_SalirButton", resourceCulture);
            }
        }
    }
}
